ucentral-client: switch from opkg to apk for package listing
Signed-off-by: John Crispin <john@phrozen.org>

diff --git a/feeds/ucentral/ucentral-client/files/etc/init.d/cpm b/feeds/ucentral/ucentral-client/files/etc/init.d/cpm
--- a/feeds/ucentral/ucentral-client/files/etc/init.d/cpm
+++ b/feeds/ucentral/ucentral-client/files/etc/init.d/cpm
@@ -5,7 +5,7 @@ STOP=01
 
 boot() {
     mkdir -p /tmp/cpm/ || { logger -t init "Failed to create /tmp/cpm"; exit 1; }
-    opkg list-installed > /tmp/packages.state || { logger -t init "Failed to list packages"; exit 1; }
+    apk list --installed > /tmp/packages.state || { logger -t init "Failed to list packages"; exit 1; }
     if [ -x /usr/share/ucentral/package_list.uc ]; then
         /usr/share/ucentral/package_list.uc || { logger -t init "Failed to execute package_list.uc"; exit 1; }
     else
