certupdate: update cert for squashfs filesystem
Signed-off-by: HaiBac <mail@bacnh.com>

diff --git a/feeds/tip/luci/luci-mod-ucentral/root/sbin/certupdate b/feeds/tip/luci/luci-mod-ucentral/root/sbin/certupdate
--- a/feeds/tip/luci/luci-mod-ucentral/root/sbin/certupdate
+++ b/feeds/tip/luci/luci-mod-ucentral/root/sbin/certupdate
@@ -6,11 +6,12 @@
 . /lib/functions.sh
 
 # amke sure the cert partition is mounted
-mount_certs
+cert_mount=$(grep certificates /proc/mounts)
+[ -z "$cert_mount" ] && mount_certs
 
-# make sure that this is a UBI volume
-ubi=$(grep certificates /proc/mounts  | tail -n 1 | grep ubi)
-[ -z "$ubi" ] && exit 1
+# validate cert volume
+cert_fs=$(grep certificates /proc/mounts | cut -d " " -f 3)
+[ "$cert_fs" != "ubifs" -a "$cert_fs" != "squashfs" ] && exit 1
 
 # extract the certificates
 mkdir -p /tmp/certs
@@ -20,16 +21,37 @@ tar x -C /tmp/certs -f /tmp/certs.tar
 [ -f /tmp/certs/cas.pem -a -f /tmp/certs/key.pem -a -f /tmp/certs/cert.pem ] || exit 1
 [ -f /tmp/certs/gateway.json -o -f /tmp/certs/dev-id ] || exit 1
 
-# copy the certificates to /etc
-cp /tmp/certs/*.pem /certificates
+case "$cert_fs" in
+	ubifs)
+		# copy the certificates to /etc
+		cp /tmp/certs/*.pem /certificates
 
-# copy dev-id or gateway.json
-for a in dev-id gateway.json; do
-	if [ -f /tmp/certs/$a ]; then
-		cp /tmp/certs/$a /certificates
-	else
-		rm -f /certificates/$a
-	fi
-done
+		# copy dev-id or gateway.json
+		for a in dev-id gateway.json; do
+			if [ -f /tmp/certs/$a ]; then
+				cp /tmp/certs/$a /certificates
+			else
+				rm -f /certificates/$a
+			fi
+		done
+		;;
+	squashfs)
+		mtd=$(find_mtd_index certificates)
+		if [ -f /tmp/certs/squashfs ]; then
+			# write the squashfs image to the cert partition
+			mtd -e /dev/mtd$mtd write /tmp/certs/squashfs /dev/mtd$mtd
+		else
+			# make a squashfs image and write it to the cert partition
+			mksquashfs /tmp/certs /tmp/certs.sqsh -comp xz -noappend
+			mtd -e /dev/mtd$mtd write /tmp/certs.sqsh /dev/mtd$mtd
+			rm -f /tmp/certs.sqsh
+		fi
+		umount /certificates
+		mount_certs
+		;;
+esac
+
+# cleanup
+rm -rf /tmp/certs /tmp/certs.tar
 
 exit 0
